#! /usr/bin/env bash

# Mailing lists
notmuch tag -inbox +list +emacs -- from:emacs-devel@gnu.org or to:emacs-devel@gnu.org
notmuch tag -inbox +list +emacs -- from:info-gnu-emacs@gnu.org or to:info-gnu-emacs@gnu.org
notmuch tag -inbox +list +emacs -- from:help-gnu-emacs@gnu.org or to:help-gnu-emacs@gnu.org
