# -*- lexical-binding:t; -*-
#+startup: fold
#+property: header-args:elisp :results silent :lexical t

* Emacs configuration
* Constants
** Directories
#+begin_src elisp
  (defconst sr/dotfiles-directory (expand-file-name "~/me/dotfiles/")
    "Root directory for dotfiles.")

  (defconst sr/emacs-load-directory
    (file-name-concat sr/dotfiles-directory "emacs/lisp/")
    "Directory for personal lisp libraries.")

  (defconst sr/note-root-directory (expand-file-name "~/me/myself/")
    "Root directory for notes.")

  (defconst sr/note-periodic-directory
    (expand-file-name "life/" sr/note-root-directory)
    "Directory for periodic notes.")

  (defconst sr/note-project-directory
    (expand-file-name "projects/" sr/note-root-directory)
    "Directory for project notes.")

  (defconst sr/note-second-brain-directory
    (expand-file-name "second-brain/" sr/note-root-directory)
    "Directory for second bran.")

  (defconst sr/note-zk-directory
    (expand-file-name "zettelkasten/" sr/note-root-directory)
    "Directory for Zettelkasten.")

  (defconst sr/note-media-directory
    (expand-file-name "media/" sr/note-root-directory)
    "Directory for media (e.g. images)")

  (defconst sr/dev-project-directory
    (expand-file-name "~/me/ws/projects/")
    "Directory for software projects")
#+end_src
** Files
#+begin_src elisp
  (defconst sr/readme-org-file-name
    (expand-file-name "emacs/README.org" sr/dotfiles-directory)
    "File name for README.org configuration file.")
#+end_src
* Package management
** Use Melpa
#+begin_src elisp
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
#+end_src
** Setup Custom
#+begin_src elisp
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (load custom-file)
#+end_src
* Environment
These are ad-hoc configurations for my local environment.
** Workaround: =Invalid function: org-element-with-disabled-cache=
[[https://www.reddit.com/r/emacs/comments/1hayavx/invalid_function_orgelementwithdisabledcache/][Reddit]]
#+begin_src elisp
  (setq native-comp-jit-compilation-deny-list '(".*org-element.*"))
  (load-library "org-element.el")
#+end_src
** mise integration
[[https://mise.jdx.dev/ide-integration.html#emacs][IDE integration with mise]]
#+begin_src elisp
  (setenv "PATH" (concat (getenv "PATH") ":/home/user/.local/share/mise/shims"))
  (setq exec-path (append exec-path '("/home/user/.local/share/mise/shims")))
#+end_src
** exec-path-from-shell
#+begin_src elisp
(when (memq window-system '(mac ns x))
  (exec-path-from-shell-initialize))
#+end_src
** macOS keyboard
#+begin_src elisp
  (setq mac-option-modifier 'meta)
#+end_src
* Enable disabled commands
#+begin_src elisp
  (put 'scroll-left 'disabled nil)
  (put 'downcase-region 'disabled nil)
#+end_src
* Load
#+begin_src elisp
  (add-to-list 'load-path sr/emacs-load-directory)
#+end_src

#+begin_src elisp
  (require 'consult)
  (require 'org)
#+end_src

Load personal packages. I'm slowly switching to per-file module setup.
#+begin_src elisp
  ;; From Prot's dotfiles
  (defmacro sr/load-configuration (name &rest body)
    "Evaluate BODY and catch any errors."
    (declare (indent 0))
    `(condition-case err
         (progn ,@body)
       ((error user-error quit)
        (message "Failed to load configuration '%s': `%S'" ,name (cdr err)))))

  (sr/load-configuration
    "Startup"
    (require 'sr-startup))

  (sr/load-configuration
    "Completion"
    (require 'sr-completion))

  (sr/load-configuration
    "Email"
    (require 'sr-email))

  (sr/load-configuration
    "Programming"
    (require 'sr-programming))

  (sr/load-configuration
    "Web"
    (require 'sr-web))

  (sr/load-configuration
    "Documentation"
    (require 'sr-documentation))

  (sr/load-configuration
    "Denote"
    (require 'sr-denote))
#+end_src
* UI and Display
** Remove bars
#+begin_src elisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src
** Set transparent title bars
#+begin_src elisp
  (set-frame-parameter nil 'ns-transparent-toolbar t)
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
#+end_src
** Title bar text
#+begin_src elisp
  (setq-default frame-title-format "")
#+end_src
** Frame options
#+begin_src elisp
  (setq frame-inhibit-implied-resize t)
#+end_src
** Font faces
Before customizing fonts, temporarily enable fixed windows
to prevent resizing windows when changing fonts.
#+begin_src elisp
  (set-face-attribute
   'default nil
   :height 150
   :family "JetBrains Mono")

  (set-face-attribute
   'variable-pitch nil
   :height 160
   :family "Pretendard Variable")
#+end_src
** Line height
#+begin_src elisp
(setq-default line-spacing 3)
#+end_src
* Custom
#+begin_src elisp
  (setq custom-unlispify-tag-names nil)
  (setq custom-unlispify-menu-entries nil)
  (setq custom-unlispify-remove-prefixes nil)
#+end_src
* Editing
** Tab bar mode
#+begin_src elisp
  (tab-bar-mode)
  (keymap-global-set "C-c <SPC>" tab-prefix-map)
  (keymap-set tab-prefix-map "]" 'tab-next)
  (keymap-set tab-prefix-map "[" 'tab-previous)
  (setq tab-bar-auto-width-max '((140) 20))
#+end_src
** Visual line mode
#+begin_src elisp
(global-visual-line-mode)
#+end_src
*** Disable on org agenda
#+begin_src elisp
  (add-hook 'org-agenda-mode-hook
            (lambda ()
              (visual-line-mode 0)))
#+end_src
** Sentences
#+begin_src elisp
  (setq sentence-end-double-space nil)
  (setq sentence-end-base "[.?!…‽,][]\"'”’)}»›]*")
#+end_src
** Mark ring
#+begin_src elisp
(setq set-mark-command-repeat-pop t)
#+end_src
** Killing
#+begin_src elisp
  (setq save-interprogram-paste-before-kill t)
  (setq kill-do-not-save-duplicates t)
#+end_src
** Registers
#+begin_src elisp
  (setopt register-use-preview 'insist)
#+end_src

Key binding for =M-x append-to-register=.
#+begin_src elisp
  (keymap-set ctl-x-r-map "a" #'append-to-register)
#+end_src
** Insert quotes more easily
#+begin_src elisp
  (defun sr/insert-quotes (&optional arg)
    "Like `insert-parentheses`, but for quotes."
    (interactive "P")
    (insert-pair arg ?\" ?\"))
  (keymap-global-set "M-\"" 'sr/insert-quotes)
#+end_src
** Toggle between let and let*
[[https://www.reddit.com/r/emacs/comments/1qyp1rk/toggle_between_let_and_let/][Source]]

#+begin_src elisp
  (defun sr/toggle-let* ()
    "Make the closest enclosing let or let* form a let* or let form, respectively,
  then reindent that form's bindings. "
    (interactive)
    (save-excursion
      (while (progn
               (condition-case nil (backward-up-list nil t) (scan-error (error "Not within a let form")))
               (not (search-forward-regexp (rx point "(" (* space) "let" (? "*") symbol-end) nil t))))
      (if (= ?* (char-before)) (backward-delete-char 1) (insert "*"))
      (indent-region (point) (progn (forward-sexp) (point)))))
#+end_src
** Clear empty lines
#+begin_src elisp
  (defun sr/clear-empty-lines ()
    "Clear empty lines on current buffer.

  When region is activated, operat on that region."
    (interactive)
    (save-restriction
      (save-excursion
        (when (use-region-p)
          (narrow-to-region (region-beginning) (region-end)))
        (goto-char (point-min))
        (delete-matching-lines "^$"))))
#+end_src
** Scrolling
#+begin_src elisp
  ;; do not let automatic scrolling recenter point.
  (setq scroll-conservatively 101)

  (setq scroll-margin 4)

  ;; adjust the point to keep the cursor at the same screen position
  ;; whenever a scroll command moves it off-window.
  (setq scroll-preserve-screen-position nil)
#+end_src
** Delete pair
#+begin_src elisp
(setq delete-pair-blink-delay 0)
(keymap-global-set "C-M-z" 'delete-pair)
#+end_src
** Macros
#+begin_src elisp
  (defalias 'sr/macro-introduction-to-logic
    (kmacro "M-m \\ { C-s SPC <return> C-b \\ } C-f & SPC ( C-M-f ) SPC <backspace> C-f \\ ( C-s & <return> C-b C-b \\ ) C-e SPC \\ \\ C-n M-m"))

  (defun sr/run-macro-introduction-to-logic ()
    (interactive)
    (let ((electric-pair-mode nil))
      (call-interactively #'sr/macro-introduction-to-logic)))

  (keymap-global-set "C-c 0" #'sr/run-macro-introduction-to-logic)
#+end_src
** Lin mode
#+begin_src elisp
  (keymap-global-set "C-c e l" #'lin-mode)
#+end_src
** Lockfiles
#+begin_src elisp
  (setq lock-file-name-transforms
        '((".*" "~/.emacs-lock-files/" t)))
#+end_src
** Which key mode
#+begin_src elisp
  (which-key-mode)
#+end_src
** Outline minor mode
#+begin_src elisp
  (keymap-global-set "<f10>" #'outline-minor-mode)
  (setq outline-minor-mode-cycle t)
  (setq outline-minor-mode-prefix "\C-c")
#+end_src
** Filling
#+begin_src elisp
  (setq-default fill-column 80)
#+end_src
* Windows
[[https://karthinks.com/software/emacs-window-management-almanac][The Emacs Window Management Almanac]] is a good reference
** Configuration
#+begin_src elisp
  (setq window-combination-resize t)
#+end_src
** Key bindings
#+begin_src elisp
  (keymap-global-set "C-M-c" #'scroll-other-window-down)
  (keymap-global-unset "C-x o")
  (keymap-global-set "M-o" #'other-window)
#+end_src
** Display-buffer
#+begin_src elisp
  (setq switch-to-buffer-obey-display-actions t)
#+end_src
** Keymap
#+begin_src elisp
  (defvar-keymap sr/window-map
    :doc "Keymap for window-related functionalities.")

  (keymap-set ctl-x-map "C-w" sr/window-map)

  ;; Remove colliding maps
  (with-eval-after-load 'org-agenda
    (keymap-unset org-agenda-mode-map "C-x C-w"))
#+end_src
** Swap states (windmove)
#+begin_src elisp
  ;; windmove

  (keymap-set sr/window-map "C-l" #'windmove-swap-states-right)
  (keymap-set sr/window-map "C-h" #'windmove-swap-states-left)
  (keymap-set sr/window-map "C-k" #'windmove-swap-states-up)
  (keymap-set sr/window-map "C-j" #'windmove-swap-states-down)
#+end_src
** Winner mode
#+begin_src elisp
  (setq winner-dont-bind-my-keys t)
  (winner-mode)

  (keymap-set sr/window-map "<left>" #'winner-undo)
  (keymap-set sr/window-map "<right>" #'winner-redo)
#+end_src
* Buffers
** Key bindings
#+begin_src elisp
  (keymap-global-set "C-x C-b" #'ibuffer)
  (keymap-global-set "<f12>" #'scratch-buffer)
#+end_src
** Default scratch buffer message
#+begin_src elisp
  (setq initial-scratch-message "\
  ;; Hi this is a scratch buffer

  ")
#+end_src
** Delete the file of the current buffer
#+begin_src elisp
  (defun sr/delete-current-file ()
    "Delete current buffer's file."
    (interactive)
    (delete-file (buffer-file-name)))
#+end_src
* Workflow
** Starting hour of a day
#+begin_src elisp
(defconst sr/note-day-start-hour 3 "The starting hour of a day for notes.")
#+end_src
** Get today for the note system
#+begin_src elisp
(defun sr/note-current-date ()
  "Return current time value for the note system. If the time is before
`sr/note-day-start-hour', return yesterday's date. Otherwise, return
today's date."
  (let* ((time (decode-time))
	 (current-day (decoded-time-day time))
	 (day (if (< (decoded-time-hour time) sr/note-day-start-hour)
		  (- current-day 1)
		current-day)))
    (encode-time (append (list 0 0 0 day) (seq-subseq time 4)))))
#+end_src
** Get file for today
#+begin_src elisp
  (defun sr/file-name-today ()
    "Return the file name for today."
    (expand-file-name
     (format-time-string "%Y-%m.org" (sr/note-current-date))
     sr/note-periodic-directory))
#+end_src
** Key map
#+begin_src elisp
  (defvar-keymap sr/workflow-map)

  (keymap-global-set "C-c j" sr/workflow-map)
#+end_src
** Open buffer for today
todo: move the point to today's entry, if needed.

#+begin_src elisp
  (defun sr/find-today-buffer ()
    "Open buffer for today's daily note."
    (interactive)
    (find-file (sr/file-name-today)))

  (keymap-set sr/workflow-map "j" #'sr/find-today-buffer)
#+end_src
** Start today
#+begin_src elisp
  (defun sr/start-today ()
    "Begin today by creating an entry to the Org buffer for today."
    (interactive)
    (find-file (sr/file-name-today))
    (goto-char (point-max))
    (unless (is-empty-line-p)
      (insert "\n"))
    (insert (concat
             "* "
             (format-time-string "%Y-%m-%d" (sr/note-current-date))))
    (recenter 0)
    (save-excursion
      (insert "\n** Logs")))
#+end_src
** Finish today
I finish each day by committing changes I made in personal files into the Git repository.

#+begin_src elisp
  (defconst sr/personal-git-repositories
    `(
      ; (,sr/dotfiles-directory . "dotfiles")
      (,sr/note-root-directory . "notes"))
    "Git repositories for personal workflow.
  Used by `sr/finish-today' for automatic daily commits.")

  (defun sr/finish-today ()
    "Finish daily workflow; save all buffers associated with a file, commit
  changes in personal repositories."
    (interactive)
    (save-some-buffers t)
    (dolist (repo sr/personal-git-repositories)
      (let ((name (cdr repo))
  	  (default-directory (car repo))
  	  (subcommands `(("add" ".")
  			 ("commit" "-m"
  			  ,(format-time-string "%Y%m%d" (sr/note-current-date)))
  			 ("push"))))
        (dolist (args subcommands)
  	(apply 'call-process (append '("git" nil nil nil) args)))
        (message (format "Commited and pushed changes in %s." name))))
    (message "Done. Good night :)"))
#+end_src
* Migration
Whenever I change my note-taking system, I need to migrate my existing
notes to the new one. I create automated scripts for this. Many of
these scripts are not well cleaned up because I expected them to be
temporary and never planned to edit then again.

I commented out the scripts I don't currently use (mostly because the
migration process is finished). I'm keeping them for now just in case
I need them later.

** Check if the current line is empty
Helper function for migration commands.

#+begin_src elisp
(defun is-empty-line-p ()
  "Return t if current line only includes whitespace, else return
nil."
  (not (not (string-match-p "^[[:blank:]]*$"
        (buffer-substring (line-beginning-position)
                          (line-end-position))))))
#+end_src
** Remove empty lines before/after headings
#+begin_src elisp
  ;; this is a quite hacky implementation; fix later
  (defun sr/org-remove-empty-lines-around-headings ()
    "Remove empty lines before and after each headings."
    (interactive)
    (org-map-entries
       (lambda ()
         (forward-line -1)
         (when (is-empty-line-p)
           (insert "##delete##"))
         (forward-line 2)
         (when (is-empty-line-p)
           (insert "##delete##")))
       nil (if (region-active-p) 'region nil))
    (save-excursion
      (goto-char (point-min))
      (delete-matching-lines "##delete##")))

  (keymap-global-set "C-c q h" 'sr/org-remove-empty-lines-around-headings)
#+end_src
** Migration from markdown
Previously, I used plain markdown documents for note taking.
Now I have to migrate from it.

I chose incremental migration. When I see a markdown note, I
explicitly call the migration command to convert to Org format. I
wanted more fine-grained control over my notes, so I needed to verify
the correctness of the conversion result.
*** Pandoc migration command
The path to the lua filter is hardcoded. This could be improved.

#+begin_src elisp
(defvar sr/pandoc-migration-command
  "pandoc --wrap=preserve -f commonmark+task_lists+yaml_metadata_block -s -t org --lua-filter=/Users/kimsaram32/me/myself/pandoc-filter.lua"
  "Command to use for `sr/migrate-to-org'.")
#+end_src
*** Convert from markdown to Org
#+begin_src elisp
  (defun sr/migrate-markdown-to-org ()
    "Convert current markdown file into Org Mode document, using Pandoc.
  Open the converted document in current buffer.
  Perform the following transformations:
  - move frontmatters (created and updated) into properties.
  - if non-ZK, remove links as they are broken."
    (interactive)
    (message "Converting markdown to Org...")
    (save-excursion
      (goto-char (point-min))
      (let* ((input-buffer (current-buffer))
  	         (input-file-name (buffer-file-name))
  	         (created-at (when (re-search-forward "^created: \\(.+\\)$" nil t)
  			                   (match-string 1)))
  	         (updated-at (when (re-search-forward "^updated: \\(.+\\)$" nil t)
  			                   (match-string 1))))
        (save-buffer)

        (with-temp-buffer
  	      (call-process-shell-command sr/pandoc-migration-command input-file-name t)
  	      (let ((temp-buffer (current-buffer)))
  	        (with-current-buffer input-buffer
  	          (replace-buffer-contents temp-buffer))))
        (goto-char (point-min))
        (goto-char (point-min))
        (org-next-visible-heading 1)
        (when created-at
  	      (org-set-property "created" created-at))
        (when updated-at
  	      (org-set-property "updated" updated-at))

        (save-excursion
          (replace-regexp "\\[\\[\\(.+?\\)\\]\\]" "\\1"))))
    (message "Done"))
#+end_src
** Automatic migration
*** Markdown indicator string
I renamed all *.md documents to *.org for easier file searching and
file name resolutions.

To distinguish old markdown documents, I included fixed indicator
strings to them.

#+begin_src elisp
(defconst sr/markdown-indicator-string "###MARKDOWN###"
  "String that indicates the current file is a markdown document.")
#+end_src
*** DWIM migration
#+begin_src elisp
  (defun sr/migrate-dwim ()
    "Migrate current file. DWIM."
    (interactive)
    (save-excursion
      (goto-char (point-min))
      (if (search-forward sr/markdown-indicator-string nil t)
          (progn
  	  (replace-match "" nil t)
  	  (while (search-forward sr/markdown-indicator-string nil t)
  	    (replace-match "" nil t))
  	  (sr/migrate-markdown-to-org))
        (sr/migrate-org-properties)
        (sr/migrate-latex)
        ;; (sr/org-remove-empty-lines-around-headings)
        )
      (message "DWIM migration finished.")))
  (keymap-global-set "C-c q m" 'sr/migrate-dwim)
#+end_src
** Migration from Obsidian documents
#+begin_src elisp
  (defun sr/migrate-insert-capture-heading ()
    "Insert heading from current buffer's name."
    (interactive)
    (let* ((split (string-split (file-name-base (buffer-name))))
  	 (time (date-to-time (nth 0 split)))
  	 (name (string-join (cdr split) " ")))
      (insert "* " (format-time-string "<%Y-%m-%d> " time) name)))
#+end_src
** Migrate inline latex
#+begin_src elisp
(defun sr/migrate-latex ()
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "\\$\\(.+?\\)\\$" nil t)
      (replace-match "\\\\(\\1\\\\)"))))
(keymap-global-set "C-c q l" 'sr/migrate-latex)
#+end_src
** Migrate old Org mode documents
#+begin_src elisp
(defun sr/migrate-org-properties ()
  "Migrate current old Org document to follow the new format. Specifically:
- move incorrect buffer options (created and updated) into properties.
- Move filetags into entry tags."
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (let ((created-at (and (re-search-forward "^#\\+created: \\(.+\\)$" nil t)
			   (let ((val (match-string 1)))
			     (beginning-of-line)
			     (delete-line)
			     val)))
	  (updated-at (and (re-search-forward "^#\\+updated: \\(.+\\)$" nil t)
			   (let ((val (match-string 1)))
			     (beginning-of-line)
			     (delete-line)
			     val)))
	  (filetags (and (re-search-forward "^#\\+filetags: \\(.+\\)$" nil t)
			   (let ((val (match-string 1)))
			     (beginning-of-line)
			     (delete-line)
			     val))))
      (org-next-visible-heading 1)
      (when created-at (org-set-property "created" created-at))
      (when updated-at (org-set-property "updated" updated-at))
      (when filetags (org-set-tags (string-replace "-" "_" filetags))))))
#+end_src
* Minibuffer
#+begin_src elisp
  (keymap-set minibuffer-mode-map "C-p" #'previous-history-element)
  (keymap-set minibuffer-mode-map "C-n" #'next-history-element)

  (setq use-short-answers t)
#+end_src
* Savehist mode
#+begin_src elisp
  (savehist-mode)
#+end_src
* Abbrev
** Abbrev tables
#+begin_src elisp
  (defun sr/define-abbrev-table (name &rest args)
    (if (boundp name)
        (clear-abbrev-table (symbol-value name)))
    (apply #'define-abbrev-table name args))

  (sr/define-abbrev-table
   'sr/latex-abbrev-table
   '(("to" "\\to")
     ("iff" "\\leftrightarrow")
     ("la" "\\land")
     ("lo" "\\lor")))

  (sr/define-abbrev-table
   'org-mode-abbrev-table
   nil
   nil
   :parents (list sr/latex-abbrev-table))
#+end_src
** Dabbrev
#+begin_src elisp
  (setq dabbrev-check-all-buffers nil)

  (defun sr/dabbrev-is-friend-buffer (other-buffer)
    "Custom function for `dabbrev-friend-buffer-function'.
  Select buffers that has the same major mode or currently attached to a
  window."
    (or (dabbrev--same-major-mode-p other-buffer)
        (get-buffer-window other-buffer)))

  (setq dabbrev-friend-buffer-function #'sr/dabbrev-is-friend-buffer)

  (setq dabbrev-abbrev-char-regexp "\\sw\\|[_<>-]")
#+end_src
* Projects
#+begin_src elisp
  (defun sr/project-other-find-file (dir)
    "Prompt for a project, and run `project-find-file' in that project."
    (interactive (list (funcall project-prompter)))
    (let ((project-current-directory-override dir))
          (call-interactively #'project-find-file)))

  (with-eval-after-load 'project
    (setq project-vc-include-untracked t)
    (setq project-mode-line t)

    (keymap-set project-prefix-map "F" #'sr/project-other-find-file))
#+end_src
* In-buffer completion
** Stack
I use the default =completion-at-point= with corfu.
** Corfu
#+begin_src elisp
  ;; corfu

  ;; Enable on these modes
  (add-hook 'sr/prog-setup-mode-hook #'corfu-mode)
  (add-hook 'minibuffer-setup-hook #'corfu-mode)
  (add-hook 'eshell-mode-hook #'corfu-mode)

  (with-eval-after-load 'corfu
    (keymap-set corfu-map "M-TAB" #'corfu-insert)
    ;; Do not complete on RET.
    (keymap-unset corfu-map "RET")

    (setq corfu-cycle t)
    (setq corfu-preview-current nil)

    ;; Popupinfo mode
    (corfu-popupinfo-mode)
    (setq corfu-popupinfo-direction '(right left vertical))
    (setq corfu-popupinfo-delay '(nil . 0))
    (setq corfu-popupinfo-max-height 20)

    ;; Autocompletions
    (setq corfu-auto t)
    (setq corfu-auto-delay 0.1)

    ;; (setq corfu-auto-trigger ".-/")
    ;; Complete on camelCase.
    (setq corfu-auto-trigger
          (concat ".-/" (apply #'string (number-sequence ?A ?Z)))))
#+end_src
* English learning
** Open dictionary for word at point
I use Merriam Webster as my dictionary. To foster my learning, I wrote
a simple function to open the word at point in the browser.

I tried using EWW to browse words inside Emacs, but the site feels
broken when rendered in pure HTML. EWW overrides
~browse-url-browser-function~ to ~eww-browse-url~, so to avoid using
EWW, I overrode it.

#+begin_src elisp
  (defcustom sr/eng-dictionary-url
    "https://www.merriam-webster.com/dictionary/%s"
    "Format string for English dictionary.")

  (defun sr/eng-browse-dictionary-at-point ()
    "Look up dictionary for a word at point."
    (interactive)
    (if-let* ((word (word-at-point t))
              (browse-url-browser-function 'browse-url-default-browser)) ; do not use EWW
        (browse-url (url-encode-url (format sr/eng-dictionary-url word)))
      (user-error "No word found at point")))

  (keymap-global-set "C-c d d" #'sr/eng-browse-dictionary-at-point)
#+end_src
* Authentication
#+begin_src elisp
  (setq auth-sources '("~/.authinfo.gpg"))
  (setq epg-pinentry-mode 'loopback)
#+end_src
* LLMs
** Agent-shell
#+begin_src elisp
  ;; acp, agent-shell

  (with-eval-after-load 'agent-shell
    (setq agent-shell-anthropic-authentication
          (agent-shell-anthropic-make-authentication :login t))

    (add-hook 'agent-shell-mode-hook #'corfu-mode))
#+end_src
* Consult (consult)
** Key bindings
#+begin_src elisp
  (keymap-global-set "C-x b" #'consult-buffer)
  (keymap-global-set "C-x 4 b" #'consult-buffer-other-window)
  (keymap-set tab-prefix-map "b" #'consult-buffer-other-tab)
  (keymap-global-set "C-x 5 b" #'consult-buffer-other-frame)
  (keymap-global-set "C-x r b" #'consult-bookmark)
  (keymap-set project-prefix-map "b" #'consult-project-buffer)

  (keymap-global-set "M-g i" #'consult-imenu)

  (keymap-global-set "M-s M-l" #'consult-line)
  (keymap-global-set "M-s g" #'consult-ripgrep)
#+end_src
** Xref
#+begin_src elisp
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
#+end_src
** Narrowing
#+begin_src elisp
  (with-eval-after-load 'consult
    (setq consult-narrow-key "<")
    (keymap-set consult-narrow-map "?" #'consult-narrow-help)
    (keymap-set consult-narrow-map "C-h" #'consult-narrow-help))
#+end_src
** Clear display-buffer-alist locally
Live preview is messed up with =display-buffer-alist=, so fix it by
temporarily resetting =display-buffer-alist=.
#+begin_src elisp
  (defun sr/consult-fix-display (consultf)
    (let ((preview (funcall consultf)))
      (lambda (action cand)
        (let ((display-buffer-alist nil))
          (funcall preview action cand)))))

  (with-eval-after-load 'consult
    (advice-add 'consult--buffer-preview :around #'sr/consult-fix-display)
    (advice-add 'consult--man-preview :around #'sr/consult-fix-display))
#+end_src
** Org integration
#+begin_src elisp
  (with-eval-after-load 'org
    (keymap-set org-mode-map "C-c C-j" #'consult-org-heading))
#+end_src
* Org
** Global key bindings
#+begin_src elisp
  ;; global keybindings.
  (keymap-global-set "C-c l" 'org-store-link)
  (keymap-global-set "C-c a" 'org-agenda)
  (keymap-global-set "C-c c" 'org-capture)
#+end_src
** General
#+begin_src elisp
  (setq org-directory sr/note-root-directory)
  (setq org-archive-location (expand-file-name
                              "archives/%s.archive::"
                              sr/note-root-directory))

  (add-to-list 'org-file-apps '("\\.md\\'" . emacs))

  (setq org-extend-today-until sr/note-day-start-hour)
#+end_src
** Editing
*** Configuration
#+begin_src elisp
  (setq org-startup-indented t)
  (setq org-startup-with-inline-images t)
  (setq-default org-startup-folded 'showeverything)

  (setq org-blank-before-new-entry '((heading . auto) (plain-list-item auto)))

  (setq org-image-actual-width nil)
  (setq org-image-max-width 400)

  (setq org-footnote-section nil)

  (setq org-list-allow-alphabetical t)

  (add-hook 'org-mode-hook #'auto-fill-mode)
  #+end_src
*** Key bindings
#+begin_src elisp
  ;; unbind conflicting keys.
  (keymap-unset org-mode-map "C-'")

  (keymap-set org-mode-map "M-{" 'org-backward-element)
  (keymap-set org-mode-map "M-}" 'org-forward-element)

  ;; alternative keybindings for arrow key related commands.
  (keymap-set org-mode-map "C-c C--" #'org-metaup)
  (keymap-set org-mode-map "C-c C-=" #'org-metadown)
  (keymap-set org-mode-map "C-c C-;" #'org-metaleft)
  (keymap-set org-mode-map "C-c C-'" #'org-metaright)

  ;; swap these two bindings, since I use the footnotes feature more.
  (keymap-set org-mode-map "C-c C-x C-f" #'org-footnote-action)
  (keymap-set org-mode-map "C-c C-x f" #'org-emphasize)

  (keymap-set org-mode-map "C-c C-8" #'org-list-make-subtree)
#+end_src
*** Insert image from clipboard (Denote integration)
#+begin_src elisp
  (defvar sr/denote-signature-for-media "media"
    "Signature to use for media files.")

  (defun sr/org-insert-image-from-clipboard ()
    "Create an image file with clipboard data and insert a link to it.
  Images are created in `sr/note-media-directory' with Denote file-naming
  scheme.

  pngpaste is used to retrieve the image from clipboard."
    (interactive)
    (let ((temp-file-name (make-temp-file "image-tmp-")))
      (when (not (eq 0 (call-process-shell-command
  		                  (format "pngpaste %s" temp-file-name)
  		                  nil nil)))
        (user-error "Attempted to paste non-image content"))
      (let* ((id (funcall denote-get-identifier-function nil nil))
             (title (denote-title-prompt nil "Image title"))
             (keywords (denote-keywords-prompt "Image keywords"))
             (extension (read-from-minibuffer "Image extension: " "."))
             (width (read-from-minibuffer "Image width (witnout units): "))
             (file-name (denote-format-file-name
                         sr/note-media-directory
                         id keywords title extension "media")))
        (copy-file temp-file-name file-name)
        (unless (string-empty-p width)
          (insert (format "#+attr_html: :width %spx\n" width)))
        (insert (format "[[media:%s]]" (car (last (file-name-split file-name))))))))

  (keymap-set org-mode-map "C-c i" #'sr/org-insert-image-from-clipboard)
#+end_src
*** Alignment for ZK structure notes
#+begin_src elisp
  (defun sr/add-zk-toc-align-rule ()
    (add-to-list
     'align-mode-rules-list
     '(zk-toc
       (regexp . "^[^;]+?;\\(\\s-+\\)\\[\\[\\S-+\\]\\]\\(\\s-+\\S-+\\)$")
       (modes . '(org-mode)))))

  (add-hook 'org-mode-hook #'sr/add-zk-toc-align-rule)
#+end_src
** Managing todo items
#+begin_src elisp
  (setq org-todo-keywords
        '((sequence "TODO" "|" "DONE" "FAILED")))
  (setq org-todo-keyword-faces
        '(("TODO" . "gold")
    	    ("WORKING" . "CadetBlue2")
    	    ("FAILED" . "brown1")))

  (setq org-deadline-warning-days 21)

  (setq org-priority-lowest 68
  	    org-priority-highest 65
  	    org-priority-default 68)

  (add-to-list 'org-modules 'habit)
#+end_src
** Latex
*** LuaLaTeX
#+begin_src elisp
  (setq luamagick '(luamagick :programs ("lualatex" "convert")
                              :description "pdf > png"
                              :message "you need to install lualatex and imagemagick."
                              :use-xcolor t
                              :image-input-type "pdf"
                              :image-output-type "png"
                              :image-size-adjust (1.0 . 1.0)
                              :latex-compiler ("lualatex -interaction nonstopmode -output-directory %o %f")
                              :image-converter ("convert -density %D -trim -antialias %f -quality 100 %O")))
  (add-to-list 'org-preview-latex-process-alist luamagick)
#+end_src
*** dvisvgm
Dvisvgm configuration is patched for my environment...
#+begin_src elisp
  (add-to-list 'org-preview-latex-process-alist
  	           '(dvisvgm :programs ("latex" "dvisvgm") :description "dvi > svg"
  		                   :message
  		                   "you need to install the programs: latex and dvisvgm."
  		                   :image-input-type "dvi" :image-output-type "svg"
  		                   :image-size-adjust (1.2 . 1.5) :latex-compiler
  		                   ("latex -interaction nonstopmode -output-directory %o %f")
  		                   :image-converter
  		                   ("TEXMFCNF=\"/usr/local/texlive/2025:$TEXMFCNF\" dvisvgm --no-fonts --exact-bbox --scale=%S --output=%O --keep %f")))
#+end_src
*** Use dvisvgm for inline preview
#+begin_src elisp
  (setq org-preview-latex-default-process 'dvisvgm)
#+end_src
*** Preview scaling
#+begin_src elisp
  (plist-put org-format-latex-options :scale 2)
#+end_src
*** Image location
#+begin_src elisp
  (setq org-preview-latex-image-directory (expand-file-name "ltximg/" sr/note-root-directory))
#+end_src
** Tags
#+begin_src elisp
  (setq org-complete-tags-always-offer-all-agenda-tags t)
  (setq org-use-tag-inheritance nil)
  (setq org-tags-match-list-sublevels t)
#+end_src
** Links
#+begin_src elisp
  (setq org-link-abbrev-alist
        `(("zk" . ,(expand-file-name "id:%s" sr/note-root-directory))
  	      ("media" . ,sr/note-media-directory)))
  (setf (cdr (assoc 'file org-link-frame-setup)) 'find-file)
#+end_src
** Source code editing and evaluation
#+begin_src elisp
  (keymap-set org-babel-map "C-k" #'org-babel-remove-result-one-or-many)

  (org-babel-do-load-languages
   'org-babel-load-languages
   '((python . t)
     (shell . t)
     (js . t)))

  (setq org-confirm-babel-evaluate nil)
  (setq org-babel-results-keyword "results")

  (setq org-edit-src-content-indentation 2)
#+end_src
** Folding
#+begin_src elisp
  (setq
   org-fold-show-context-detail
   '((isearch . lineage)
     (default . tree)))
#+end_src
** Identifiers
#+begin_src elisp
  (setq org-id-method 'uuid)
  (setq org-id-track-globally t)
  (setq org-id-search-archives nil)
#+end_src
** Agenda (org-agenda)
#+begin_src elisp
  (with-eval-after-load 'org-agenda
    (setq
     org-agenda-files
     (list sr/note-root-directory
           sr/note-second-brain-directory
    			 (expand-file-name "projects/" sr/note-root-directory)
    			 sr/note-zk-directory))

    (setq org-agenda-restore-windows-after-quit t)

    (setq org-agenda-todo-ignore-deadlines -1)
    (setq org-agenda-skip-deadline-prewarning-if-scheduled t)
    (setq org-agenda-skip-timestamp-if-deadline-is-shown t)
    (setq org-agenda-sorting-strategy
          '((agenda habit-up priority-down deadline-up category-keep)
    	      (todo urgency-down category-keep)
    	      (tags urgency-down category-keep)
    	      (search category-keep)))

    (setq org-agenda-span 14)
    (setq
     'org-agenda-custom-commands
     '(("d" "Daily agenda"
  	    ((agenda ""
  		           ((org-agenda-span 'day)
  		            (org-deadline-past-days 0)
  		            (org-agenda-deadline-faces
  		             '((1.0 . org-scheduled-today)
  		               (0.5 . org-scheduled)
  		               (0.0 . org-scheduled)))
  		            (org-agenda-overriding-header "Events")
  		            (org-super-agenda-groups
  		             '((:name "Events"
  			                    :tag ("event"))
  		               (:discard (:anything))))
  		            (org-agenda-buffer-name "*Org Daily Agenda*")))

  	     (agenda ""
  		           ((org-agenda-span 'day)
  		            (org-agenda-overriding-header "Today")
  		            (org-super-agenda-groups
  		             '((:discard (:tag "event"))
                     (:name "Goals"
                            :tag ("#weekly" "#monthly" "okr"))
  		               (:name "School"
  			                    :tag ("schoolwork" "내신"))
                     (:name "Work"
  			                    :tag ("work"))
  		               (:name "Todo"
  			                    :and (:todo ("TODO" "WORKING")
                                        :not (:tag "trivial")))
                     (:name "Trivial tasks"
  			                    :and (:todo ("TODO" "WORKING")
  					                            :tag "trivial"))
                     (:name "ZK"
                            :category "zk")
  		               (:name "Journals"
  			                    :tag "journal"
  			                    :order 2)
  		               (:name "Second brain"
                            :category ("capture" "aor" "project" "archive")
                            :order 2)
                     (:name "Today"
  			                    :time-grid t)))))))))

    (require 'org-super-agenda)
    (org-super-agenda-mode))
#+end_src
** Capturing (org-capture)
#+begin_src elisp
  (with-eval-after-load 'org-capture
    (keymap-unset org-capture-mode-map "C-c C-c")
    (keymap-set org-capture-mode-map "C-c C-f" 'org-capture-finalize)

    (setq
     org-capture-templates

     `(
       ;; todo files
       ("t" "Todo"
        entry (file ,(expand-file-name "todo.org" sr/note-root-directory))
        "* TODO %?"
        :prepend t)

       ;; coding interview preparation
       ("p" "Problem")
       ("pb" "Baekjoon problem"
        entry (file ,(expand-file-name "problems/baekjoon.org" sr/note-root-directory))
        "* %t %^{id}. %^{title}
  [[https://www.acmicpc.net/problem/%\\1][Baekjoon]]
  ,** Ideas
  %?"
        :jump-to-captured t)
       ("pp" "Programmers problem"
        entry (file ,(expand-file-name "problems/programmers.org" sr/note-root-directory))
        "* %t %^{id}. %^{title}
  [[%^{url}][Programmers]]
  ,** Ideas
  %?"
        :jump-to-captured t)))
#+end_src
** Bookmark support (org-bookmark-heading)
#+begin_src elisp
  (require 'org-bookmark-heading)
#+end_src
** COMMENT Social (org-social)
#+begin_src elisp
  (require 'org-social)
  (setq org-social-file (expand-file-name "org_social_vfile" user-emacs-directory))
  (setq org-social-relay "https://relay.org-social.org/")
  (setq org-social-my-public-url "https://host.org-social.org/saram/social.org")
#+end_src
* Dired
#+begin_src elisp
  (with-eval-after-load 'dired
    (setq dired-listing-switches "-hal")
    (setq dired-auto-revert-buffer t)

    (setq delete-by-moving-to-trash t)

    (add-hook 'dired-mode-hook 'dired-omit-mode)
    (add-hook 'dired-mode-hook 'lin-mode))

#+end_src
* Version control and diffing
** Magit & Forge
#+begin_src elisp
  ;; forge

  (defun sr/forge-copy-browse-url-as-link ()
    (interactive)
    (when-let* ((target (forge--browse-target))
              (url (if (stringp target) target (forge-get-url target))))
      (kill-new (format "[[%s]]" url))
      (message url)))

  (with-eval-after-load 'magit
    (keymap-set magit-mode-map "C-c C-l" #'sr/forge-copy-browse-url-as-link))
#+end_src
* Elfeed
#+begin_src elisp
  (require 'elfeed)
#+end_src
** Key bindings
#+begin_src elisp
  (keymap-global-set "C-c w" 'elfeed)
#+end_src
** Default search filter
#+begin_src elisp
  (setq elfeed-search-filter "+unread")
#+end_src
** EWW Integration
#+begin_src elisp
  (defun sr/elfeed-show-visit-eww ()
    "Visit the current entry with `eww'."
    (interactive)
    (when-let ((link (elfeed-entry-link elfeed-show-entry)))
      (eww link)))

  (keymap-set elfeed-show-mode-map "w" 'sr/elfeed-show-visit-eww)
#+end_src
** Managing 'to read' entries
I often copy my elfeed entries to my iPhone so I can read them while
walking around.

#+begin_src elisp
  (defvar sr/elfeed-to-read-tag 'to-read-list
    "Elfeed tag for 'to read' entries.")
#+end_src

My workflow is as follows: I go through the unread entries, and for
each entry, I hit =a= to add it, and =f= to skip it. When I'm done, I
export the entries to clipboard, paste them to the Notes app, and read
them on my iPhone.

When I come back, I process the entries intoto fleeting notes. Then, I
mark the entries as read.

*** Add current entry to the list with =a=
#+begin_src elisp
  (defun sr/elfeed-show-add-to-read ()
    "Add current entry to 'to read' list and go to the next entry."
    (interactive)
    (when-let ((entry elfeed-show-entry))
      (elfeed-show-tag 'unread sr/elfeed-to-read-tag)
      (message "Addded entry to to-read list")
      (elfeed-show-next)))

  (keymap-set elfeed-show-mode-map "a" 'sr/elfeed-show-add-to-read)
#+end_src
*** Skip current entry with =f=
#+begin_src elisp
  (defun sr/elfeed-show-skip ()
    "Skip the current entry.

  Mark the entry as unread and go to the next entry."
    (interactive)
    (elfeed-show-tag 'unread)
    (elfeed-show-next))

  (keymap-set elfeed-show-mode-map "f" #'sr/elfeed-show-skip)
#+end_src
*** Export the entries with =l= and =e=
Currently, exporting is done by pushing items to the mark ring. I
export the entries just before I leave, so I apply the filter to show
only the entries in the reading list after I come back.

#+begin_src elisp
  (defun sr/elfeed-search-show-to-reads ()
    "Set Elfeed filter to show 'to read' entries only."
    (interactive)
    (elfeed-search-set-filter "+to-read-list"))

  (defun sr/elfeed-export-entries ()
    "Push current entries to the mark ring."
    (interactive)
    (kill-new (string-join
  	     (mapcar
  	      (lambda (entry) (elfeed-entry-link entry))
  	      (if (region-active-p)
              (elfeed-search-selected)
            elfeed-search-entries))
  	     "\n"))
    (message "Pushed current entries to the mark ring."))

  (keymap-set elfeed-search-mode-map "l" 'sr/elfeed-search-show-to-reads)
  (keymap-set elfeed-search-mode-map "e" 'sr/elfeed-export-entries)
#+end_src
** Mark entries as read
In search mode:
#+begin_src elisp
  (defun sr/elfeed-search-read ()
    "Read elfeed entries in search mode."
    (interactive)
    (let ((entries (elfeed-search-selected)))
      (elfeed-untag entries 'unread)
      (elfeed-untag entries sr/elfeed-to-read-tag)
      (mapc #'elfeed-search-update-entry entries)
      (unless (or elfeed-search-remain-on-entry (use-region-p))
        (forward-line))))

  (keymap-set elfeed-search-mode-map "r" #'sr/elfeed-search-read)
#+end_src

In show mode:
#+begin_src elisp
  (defun sr/elfeed-show-read ()
    "Read current elfeed entry."
    (interactive)
    (elfeed-show-untag 'unread 'to-read-list))

  (keymap-set elfeed-show-mode-map "r" #'sr/elfeed-show-read)
#+end_src
** Load entries
#+begin_src elisp
  (defun sr/elfeed-load-entries ()
    "Load entries from elfeed.org."
    (interactive)
    (org-babel-load-file (expand-file-name "emacs/elfeed.org" sr/dotfiles-directory))
    (elfeed-update))

  (sr/elfeed-load-entries)
#+end_src
* Themes
#+begin_src elisp
  ;; Modus themes
  (require-theme 'modus-themes)
  (keymap-global-set "<f5>" 'modus-themes-rotate)
  (setq modus-themes-common-palette-overrides modus-themes-preset-overrides-faint)
  (modus-themes-load-theme 'modus-vivendi-tinted)

  ;; Ef themes
  (require-theme 'ef-themes)
  (ef-themes-take-over-modus-themes-mode 1)
#+end_src
* Spray
#+begin_src elisp
  (keymap-global-set "<f6>" #'spray-mode)
#+end_src
* Avy
#+begin_src elisp
  (with-eval-after-load 'avy
    (keymap-global-set "C-M-'" #'avy-goto-char-timer)
    (keymap-global-set "M-g t" #'avy-goto-char-2)
    (keymap-global-set "M-g b" #'avy-goto-char)

    (setq avy-timeout-seconds 0.3)
    ;; I use Colemak layout, so the keys are adjusted accordingly.
    ;; The default is '(?a ?s ?d ?f ?g ?h ?j ?k ?l).
    (setq avy-keys '(?a ?r ?s ?t ?d ?n ?e ?i ?o ?h)))
#+end_src
* Tools
#+begin_src elisp
  (defvar-keymap sr/external-tools-map
    :doc "Keymap for various tools.")

  (keymap-global-set "C-c e" sr/external-tools-map)

  ;; evil-mode
  (keymap-set sr/external-tools-map "e" #'evil-mode)

  ;; docker
  (keymap-set sr/external-tools-map "d" #'docker)
#+end_src
** Kele
#+begin_src elisp
  (require 'kele)
#+end_src

=kele-mode= is not enabled by default, because the cluster might be
unreachable at startup. When this is the case, Kele still tries to
connect, causing Emacs to freeze on launch.

#+begin_src elisp
  (keymap-set kele-mode-map "C-c k" kele-command-map)
#+end_src
* LaTeX editing
** AUCTeX
#+begin_src elisp
  (require 'auctex)
  (require 'tex)
  (require 'latex)
#+end_src

[[info:auctex#Quick Start][auctex#Quick Start]]

#+begin_src elisp
  (setq TeX-auto-save t)
  (setq TeX-parse-self t)
#+end_src

#+begin_src elisp
  (setq-default TeX-master t)
#+end_src

[[info:auctex#Starting Viewers][auctex#Starting Viewers]]

I wrote my own viewer program, since the one with pdf-tools
integration doesn't work for me.

#+begin_src elisp
  (defun sr/TeX-open-pdf-as-buffer ()
    "Open the pdf output as a buffer.
  Used in `TeX-view-program-list'."
    (unless TeX-PDF-mode
      (error "PDF Tools only work with PDF output"))
    (let* ((pdf (TeX-active-master (TeX-output-extension)))
           (buffer (or (find-buffer-visiting pdf)
                       (find-file-noselect pdf))))
      (display-buffer buffer)))

  (add-to-list
   'TeX-view-program-list
   '("PDF Buffer" sr/TeX-open-pdf-as-buffer))

  (add-to-list
   'TeX-view-program-selection
   '(output-pdf "PDF Buffer"))
#+end_src

Do not ask before saving.

#+begin_src elisp
  (setq TeX-save-query nil)
#+end_src
** Assist mode
Insert symbols using shortcuts. This is almost identical to cdlatex. I
tried cdlatex but setting it up for my own workflow was kind of a
pain. So I ended up building my own solution.

#+begin_src elisp
  (defvar-keymap sr/latex-assist-mode-map)

  (defvar sr/latex-assist-symbol-prefix nil)

  (defvar-keymap sr/latex-assist-symbol-1-map)
  (defvar-keymap sr/latex-assist-symbol-2-map)
  (defvar-keymap sr/latex-assist-symbol-3-map)

  (defun sr/latex-assist-set-symbol-keys (defs)
    (pcase-dolist (`(,key ,ex1 ,ex2 ,ex3) defs)
      (when (not (key-valid-p key))
        (user-error "Not a valid key"))
      (when (string= key sr/latex-assist-symbol-prefix)
        (user-error "Cannot use the prefix key"))

      (when ex1
        (keymap-set sr/latex-assist-symbol-1-map key (lambda ()
                                                       (interactive)
                                                       (insert ex1))))
      (when ex2
        (keymap-set sr/latex-assist-symbol-2-map key (lambda ()
                                                       (interactive)
                                                       (insert ex2))))
      (when ex3
        (keymap-set sr/latex-assist-symbol-3-map key (lambda ()
                                                       (interactive)
                                                       (insert ex3))))))

  (defun sr/latex-assist-set-symbol-prefix (prefix)
    (when (not (key-valid-p prefix))
      (user-error "Not a valid key"))

    (when sr/latex-assist-symbol-prefix
      (keymap-unset sr/latex-assist-mode-map sr/latex-assist-symbol-prefix)
      (keymap-unset sr/latex-assist-symbol-1-map sr/latex-assist-symbol-prefix)
      (keymap-unset sr/latex-assist-symbol-2-map sr/latex-assist-symbol-prefix))

    (keymap-set sr/latex-assist-mode-map prefix sr/latex-assist-symbol-1-map)
    (keymap-set sr/latex-assist-symbol-1-map prefix sr/latex-assist-symbol-2-map)
    (keymap-set sr/latex-assist-symbol-2-map prefix sr/latex-assist-symbol-3-map)

    (setq sr/latex-assist-symbol-prefix prefix))

  (define-minor-mode sr/latex-assist-mode
    "Minor mode for quicker LaTeX editings."
    :lighter "Latex Assist"
    :init-value nil)

  (sr/latex-assist-set-symbol-prefix "'")

  (sr/latex-assist-set-symbol-keys
   '(("a" "\\alpha" "\\land")
     ("A" "\\forall" "\\aleph")
     ("b" "\\beta")
     ("e" "\\exists ")
     ("v" "\\lor")
     ("-" "\\neg{")
     ("." " \\cdot ")
     ("," " \\circ ")
     ("p" "^\\prime")))
#+end_src
** Math-delimiters
#+begin_src elisp
  ;; math-delimiters

  (keymap-set org-mode-map "$" #'math-delimiters-insert)
  (keymap-set LaTeX-mode-map "$" #'math-delimiters-insert)
#+end_src
* Vterm
#+begin_src elisp
  ;; vterm, vterm-toggle

  (with-eval-after-load 'vterm
    (keymap-set vterm-mode-map "C-M-;" #'vterm-copy-mode)
    (keymap-set vterm-copy-mode-map "C-M-;" #'vterm-copy-mode)

    (keymap-set vterm-mode-map "C-c C-l" #'vterm-clear)

    (keymap-set vterm-mode-map "C-c C-n" #'vterm-toggle-forward)
    (keymap-set vterm-mode-map "C-c C-p" #'vterm-toggle-backward))

  (defvar sr/vterm-switch-function #'vterm-other-window
    "Function for switching to a vterm buffer.
  It should accept the same arguments as `vterm'.")

  (defun sr/vterm-switch-and-cd (arg)
    "Switch to a vterm buffer and cd to current directory.
  ARG has the same meaning as `vterm'."
    (interactive "P")
    (let* ((directory (expand-file-name default-directory))
           (command (concat
                     "cd "
                     (shell-quote-argument directory))))
      (with-current-buffer (funcall sr/vterm-switch-function arg)
        (vterm-send-string "\C-u") ; clear the current line
        (vterm-send-string command)
        (vterm-send-string "\C-m") ; CR
        (cd directory))))

  (keymap-global-set "C-c e t" #'sr/vterm-switch-and-cd)
#+end_src
* Window setup
#+begin_src elisp
  (setq display-buffer-alist nil)
#+end_src
** COMMENT Org mode source code editing
~org-src-mode~ is a minor mode enabled when editing source code in Org mode.

#+begin_src elisp
  (setq org-src-window-setup 'plain)
  (add-to-list 'display-buffer-alist
  	     `(,(lambda (&rest args) org-src-mode)
  	       (display-buffer-at-bottom)))
#+end_src
** Side window (bottom): Help and occur
#+begin_src elisp
  (add-to-list
   'display-buffer-alist
   `((or
  		(derived-mode help-mode)
      (derived-mode helpful-mode)
  		(derived-mode occur-mode))
  	 (display-buffer-in-side-window)
  	 (side . bottom)
  	 (window-height . 0.4)
  	 (post-command-select-window . t)))
#+end_src
** Side window (right): Info and apropos
#+begin_src elisp
  (add-to-list
   'display-buffer-alist
   `((or
  		(derived-mode Info-mode)
  		(derived-mode apropos-mode))
  	 (display-buffer-reuse-mode-window display-buffer-in-side-window)
  	 (mode . Info-mode)
  	 (side . right)
  	 (window-width . 0.5)
  	 (post-command-select-window . t)))
#+end_src
** Manuals
#+begin_src elisp
  (defconst sr/manual-mode-list
    '(Man-mode kubedoc-mode)
    "List of major modes that function as manuals.")

  (add-to-list
   'display-buffer-alist
   `((or
      ,@(mapcar (lambda (x) (list 'derived-mode x)) sr/manual-mode-list))
     (display-buffer-reuse-mode-window display-buffer-in-side-window)
     (mode . ,sr/manual-mode-list)
     (side . right)
     (window-width . 0.5)
     (post-command-select-window . t)))
#+end_src

Man specific configs.
#+begin_src elisp
  (setq Man-notify-method 'thrifty)

  (add-hook 'Man-mode-hook (lambda ()
  			  (set-window-dedicated-p (selected-window) nil)))
#+end_src
** Tabulated list mode
Major mode for browsing a list of items e.g. Docker mode.

#+begin_src elisp
  (add-to-list
   'display-buffer-alist
   `((derived-mode tabulated-list-mode)
  	 (display-buffer-in-side-window)
  	 (side . bottom)
     (window-height . 0.5)
  	 (post-command-select-window . t)))
#+end_src
** Eldoc
#+begin_src elisp
  (add-to-list
   'display-buffer-alist
   `("^\\*eldoc"
     (display-buffer-in-side-window)
     (side . bottom)
     (window-height . 20)
     (post-command-select-window . t)))
#+end_src
